name: 'Vault access'
inputs:
  environment:
    required: true
    type: string
  branch:
    required: true
    type: string

runs:
  using: 'composite'
  steps:

    - name: Deploy 
      run: |
        echo "Deploying to ${{ inputs.environment }} environment inside actions"
      shell: bash