name: 'Vault access'
inputs:
  environment:
    required: true
    type: string
  branch:
    required: true
    type: string
  aws-access-key-id:
    description: 'AWS Access Key ID'
    required: true
  aws-secret-access-key:
    description: 'AWS Secret Access Key'
    required: true

runs:
  using: 'composite'
  steps:

    # - name: Configure AWS credentials
    #   uses: aws-actions/configure-aws-credentials@v4.0.2
    #   with:
    #     aws-access-key-id: ${{ inputs.aws-access-key-id }}
    #     aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
    #     aws-region: eu-west-1

    - name: Checkout Service Code
      uses: actions/checkout@v4.2.0
      with:
        path: service-repo
      
    - name: Terraform Init and Validate
      working-directory: service-repo/terraform
      id: terraform-init-validate
      run: |
        
        terraform init -backend=false
          #-backend=true
          #-backend-config="bucket=my-bucket" \
          #-backend-config="key=my-key" \
          #-backend-config="region=my-region" \
          #-backend-config="dynamodb_table=terraform-locks" \
          #-backend-config="encrypt=true"
        
        # Validate the Terraform configuration
        terraform validate

        # Generate a plan
        terraform plan -out=plan.tfplan -lock=false
      shell: bash