name: 'Vault access'
inputs:
  environment:
    required: true
    type: string
  branch:
    required: true
    type: string

runs:
  using: 'composite'
  steps:

    - name: Checkout Service Code
      uses: actions/checkout@v4.2.0
      with:
        token: ${{ secrets.TOKEN }}
      
    - name: Terraform Validate
      working-directory: terraform
      id: terraform-validate
      run: |
        ls
        terraform init -backend=false
        terraform validate
      shell: bash