name: 'Vault access'
inputs:
  environment:
    required: true
    type: string
  branch:
    required: true
    type: string

runs:
  using: 'composite'
  steps:

    - name: Checkout Service Code
      uses: actions/checkout@v4.2.0
      with:
        path: service-repo
      
    - name: Terraform Init and Validate
      working-directory: service-repo/terraform
      id: terraform-init-validate
      run: |
        
        terraform init -backend=true 
          #-backend-config="bucket=my-bucket" \
          #-backend-config="key=my-key" \
          3-backend-config="region=my-region" \
          #-backend-config="dynamodb_table=terraform-locks" \
          #-backend-config="encrypt=true"
        
        # Validate the Terraform configuration
        terraform validate

        # Generate a plan
        terraform plan -out=plan.tfplan
      shell: bash